### ISSUE TITLE
Embed Videos & automated subtitles translation

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#10]
Runestone supports embedding [video](http://runestoneinteractive.org/build/html/directives/video.html)

Lessons should be adapted to include video presentations, see [youtube playlist](https://www.youtube.com/playlist?list=PLUukMN0DTKCtbzhbYe2jdF4cr8MOWClXc) (original course)

Please include at least subtitles (see youtube API and translate it providing an automated mechanism).

**Comment by urstrulykkr** [comment]
Working on this too .

**Comment by urstrulykkr** [comment]
> Please include at least subtitles

To which language do I need to translate ?

**Comment by IronVenom** [comment]
I am working on this as well. Can you tell me in which sequence are we supposed to embed the videos in the lectures? And are we supposed to create subtitles in English?

**Comment by urstrulykkr** [comment]
@reingart  I had embedded the videos and working on the translation API, do you want the content to be translated in english?

**Comment by IronVenom** [comment]
I have embedded the lectures and published a static website to the progress - PyAr/PyZombis#15. While adding the English subtitles, I am having some problems. I have tried the following two approaches -

- Added cc_lang_pref = 'en' and cc_load_policy = 1 in the id of the video, but Runestone takes in only one argument.
- I changed the function onYouTubeIframeAPIReady() in runestonevideo.js file present in the _static folder, to this - 

function onYouTubeIframeAPIReady() {
	let videolist = $(".youtube-video");
	videolist.each( function(i, video) {
		player = new YT.Player($(video).data("video-divid"), {
			'height': $(video).data("video-height"),
			'width': $(video).data("video-width"),
			'videoId': $(video).data("video-videoid"),

			'events': {
				'onStateChange': onPlayerStateChange
			},

            playerVars: {
                'start' : $(video).data("video-start"),
                cc_load_policy: 1,
                cc_lang_pref: 'en',
                'end' : $(video).data("video-end")
        });
	});
}
However, when I rebuild the folder, the original file gets restored, and again the captions and subtitles are not delivered. If I serve it without building, it uses the default setup, due to which again the subtitles are not built.

**Comment by urstrulykkr** [comment]
Same here @reingart I took have some issues with that ..

**Comment by reingart** [comment]
Thank you both @urstrulykkr & @IronVenom for the collaboration and interest!

At this stage for GSoC, it is not expected that you resolve complex tickets like this completely.
It is more important that you document the approach & publish a initial code (Proof-of-Concept), to spot any potential difficulties and think on possible solutions in advance.

It is probably we will need to debug and / or adapt Runestone & Sphynx components and libraries.
You could look at Runestone source code for more insights.

Translations should target Spanish language, but it would be great if this course could be further translated to other languages too (specially English, that possibly we must use as a base)

**Comment by urstrulykkr** [comment]
@reingart  I should even appreciate your patience. Without you we won't be able to make this out. I will try my level best to be a GSoC student under you.
Is it compulsory to solve all the issues ?
Cos I'm focusing on my proposal for now and have my university exams ahead..
But still will try to contribute.
